//! The complete armory: 3 original weapons and 30 additions. Stable enum names
//! preserve existing saves; every entry supplies gameplay, presentation and loot.
use serde::{Deserialize, Serialize};
#[derive(Clone, Copy, PartialEq, Eq, Serialize, Deserialize, Debug)]
pub enum WeaponKind {
    Pistol,
    Double,
    Repeater,
    GraveRevolver,
    Duelist,
    Pepperbox,
    HandCannon,
    Needler,
    Blunderbuss,
    Coachgun,
    SlugGun,
    Dragonbreath,
    Frostbite,
    Longrifle,
    Carbine,
    Gatling,
    Harpoon,
    Ricochet,
    GrenadeLauncher,
    Mortar,
    EmberStaff,
    StormWand,
    FrostScepter,
    SoulLantern,
    PlagueCenser,
    Crossbow,
    Longbow,
    Cleaver,
    Rapier,
    Warhammer,
    Scythe,
    ChainFlail,
    TwinDaggers,
}
/// Burning creatures lose this much health per second, for this long after
/// each hit.
pub const BURN_DPS: f32 = 18.;
pub const BURN_SECONDS: f32 = 3.;
/// Venom: each hit adds time, up to a cap, and drains this much per second.
pub const VENOM_DPS: f32 = 12.;
pub const VENOM_PER_HIT: f32 = 1.8;
pub const VENOM_MAX: f32 = 6.;
#[derive(Clone, Copy, PartialEq, Eq, Debug)]
pub enum Effect {
    Impact,
    Pierce,
    Burn,
    Frost,
    Poison,
    Chain,
    Drain,
    Pull,
    Blast,
}
impl Effect {
    /// One word for the card face, or `None` for a plain impact.
    pub fn tag(self) -> Option<&'static str> {
        Some(match self {
            Effect::Impact => return None,
            Effect::Pierce => "PIERCE",
            Effect::Burn => "BURN",
            Effect::Frost => "FROST",
            Effect::Poison => "VENOM",
            Effect::Chain => "CHAIN",
            Effect::Drain => "DRAIN",
            Effect::Pull => "PULL",
            Effect::Blast => "SPLASH",
        })
    }
}
#[derive(Clone, Copy, PartialEq, Eq)]
pub enum Model {
    Pistol,
    Shotgun,
    Rifle,
    Revolver,
    Cannon,
    Needle,
    Gatling,
    Staff,
    Lantern,
    Crossbow,
    Bow,
    Blade,
    Rapier,
    Hammer,
    Scythe,
    Flail,
    Daggers,
}
#[derive(Clone, Copy)]
pub struct Spec {
    pub name: &'static str,
    pub group: usize,
    pub model: Model,
    pub effect: Effect,
    pub description: &'static str,
    pub damage: f32,
    pub capacity: u32,
    pub interval: f32,
    pub reload: f32,
    pub pellets: u32,
    pub range: f32,
    pub spread: f32,
    pub radius: f32,
    pub projectile: f32,
    pub burst: u32,
    pub knockback: f32,
}
macro_rules! w {
    ($name:literal,$group:expr,$model:ident,$effect:ident,$desc:literal,$damage:expr,$cap:expr,$interval:expr,$reload:expr,$pellets:expr,$range:expr,$spread:expr,$radius:expr,$speed:expr,$burst:expr,$push:expr) => {
        Spec {
            name: $name,
            group: $group,
            model: Model::$model,
            effect: Effect::$effect,
            description: $desc,
            damage: $damage,
            capacity: $cap,
            interval: $interval,
            reload: $reload,
            pellets: $pellets,
            range: $range,
            spread: $spread,
            radius: $radius,
            projectile: $speed,
            burst: $burst,
            knockback: $push,
        }
    };
}
pub const GROUPS: [&str; 6] = [
    "Sidearms",
    "Scatterguns",
    "Longarms",
    "Ordnance",
    "Occult",
    "Melee",
];
pub const SPECS: [Spec; 33] = [
    w!(
        "IRON",
        0,
        Pistol,
        Impact,
        "Reliable eight-round sidearm.",
        30.,
        8,
        0.27,
        1.65,
        1,
        40.,
        0.012,
        0.,
        0.,
        1,
        0.1
    ),
    w!(
        "DOUBLE",
        1,
        Shotgun,
        Impact,
        "Seven pellets. Two barrels. Brutal up close.",
        16.,
        2,
        0.65,
        2.35,
        7,
        24.,
        0.10,
        0.,
        0.,
        1,
        0.12
    ),
    w!(
        "REPEATER",
        2,
        Rifle,
        Impact,
        "Sustained automatic fire, generous magazine.",
        17.,
        24,
        0.105,
        1.9,
        1,
        35.,
        0.028,
        0.,
        0.,
        1,
        0.05
    ),
    w!(
        "GRAVE REVOLVER",
        0,
        Revolver,
        Impact,
        "Heavy rounds knock enemies off their approach.",
        49.,
        6,
        0.48,
        2.,
        1,
        36.,
        0.015,
        0.,
        0.,
        1,
        0.65
    ),
    w!(
        "DUELIST",
        0,
        Pistol,
        Pierce,
        "Quick, precise shots pierce two lined-up targets.",
        23.,
        10,
        0.22,
        1.5,
        1,
        42.,
        0.003,
        0.,
        0.,
        1,
        0.06
    ),
    w!(
        "PEPPERBOX",
        0,
        Revolver,
        Impact,
        "Four-shot clusters from a rotating barrel bank.",
        14.,
        12,
        0.42,
        2.,
        4,
        20.,
        0.13,
        0.,
        0.,
        1,
        0.15
    ),
    w!(
        "HAND CANNON",
        0,
        Cannon,
        Blast,
        "A compact explosive slug with a small blast.",
        66.,
        3,
        0.85,
        2.3,
        1,
        30.,
        0.018,
        2.,
        24.,
        1,
        0.5
    ),
    w!(
        "NEEDLER",
        0,
        Needle,
        Poison,
        "Rapid darts poison their targets for three seconds.",
        10.,
        20,
        0.12,
        1.7,
        1,
        28.,
        0.014,
        0.,
        30.,
        1,
        0.
    ),
    w!(
        "BLUNDERBUSS",
        1,
        Shotgun,
        Impact,
        "Twelve-pellet spread; devastating at close range.",
        13.,
        1,
        0.9,
        2.1,
        12,
        15.,
        0.26,
        0.,
        0.,
        1,
        0.22
    ),
    w!(
        "COACHGUN",
        1,
        Shotgun,
        Impact,
        "A wide blast shoves an advancing crowd back.",
        12.,
        2,
        0.48,
        2.1,
        9,
        18.,
        0.19,
        0.,
        0.,
        1,
        0.32
    ),
    w!(
        "SLUGBREAKER",
        1,
        Shotgun,
        Pierce,
        "One heavy slug tears through three enemies.",
        95.,
        4,
        0.8,
        2.4,
        1,
        48.,
        0.006,
        0.,
        0.,
        1,
        0.45
    ),
    w!(
        "DRAGONBREATH",
        1,
        Shotgun,
        Burn,
        "Six incendiary pellets leave enemies burning.",
        11.,
        2,
        0.78,
        2.5,
        6,
        18.,
        0.15,
        0.,
        0.,
        1,
        0.12
    ),
    w!(
        "FROSTBITE",
        1,
        Shotgun,
        Frost,
        "An icy spread slows a pack for three seconds.",
        12.,
        3,
        0.72,
        2.3,
        6,
        21.,
        0.13,
        0.,
        0.,
        1,
        0.1
    ),
    w!(
        "LONGRIFLE",
        2,
        Rifle,
        Pierce,
        "Slow, precise fire punches through an entire line.",
        108.,
        5,
        1.15,
        2.6,
        1,
        70.,
        0.001,
        0.,
        0.,
        1,
        0.4
    ),
    w!(
        "BLACKTHORN",
        2,
        Rifle,
        Impact,
        "Three-round bursts with controlled recoil.",
        23.,
        18,
        0.52,
        2.,
        1,
        42.,
        0.013,
        0.,
        0.,
        3,
        0.08
    ),
    w!(
        "GRAVEMILL",
        2,
        Gatling,
        Impact,
        "Fire accelerates as the barrel bank spins up.",
        12.,
        60,
        0.15,
        3.1,
        1,
        32.,
        0.045,
        0.,
        0.,
        1,
        0.03
    ),
    w!(
        "HARPOON",
        2,
        Crossbow,
        Pull,
        "Barbed bolts drag the victim toward you.",
        62.,
        1,
        1.1,
        1.65,
        1,
        32.,
        0.002,
        0.,
        28.,
        1,
        -2.3
    ),
    w!(
        "RICOCHET",
        2,
        Rifle,
        Chain,
        "Rounds ricochet to two nearby enemies.",
        36.,
        9,
        0.48,
        1.9,
        1,
        38.,
        0.009,
        5.,
        0.,
        1,
        0.1
    ),
    w!(
        "GRAVEDIGGER",
        3,
        Cannon,
        Blast,
        "Arcing grenades detonate in a four-metre blast.",
        92.,
        4,
        0.95,
        2.8,
        1,
        36.,
        0.018,
        4.,
        15.,
        1,
        1.
    ),
    w!(
        "BELL MORTAR",
        3,
        Cannon,
        Blast,
        "A slow arcing shell clears a broad area.",
        145.,
        1,
        1.4,
        3.,
        1,
        42.,
        0.012,
        5.8,
        12.,
        1,
        1.8
    ),
    w!(
        "EMBER STAFF",
        4,
        Staff,
        Burn,
        "Fire orbs splash and burn clustered enemies.",
        35.,
        12,
        0.48,
        2.,
        1,
        35.,
        0.01,
        2.4,
        18.,
        1,
        0.15
    ),
    w!(
        "STORM WAND",
        4,
        Staff,
        Chain,
        "Lightning jumps through three nearby targets.",
        39.,
        10,
        0.6,
        2.,
        1,
        30.,
        0.,
        6.5,
        0.,
        1,
        0.
    ),
    w!(
        "RIME SCEPTER",
        4,
        Staff,
        Frost,
        "A frost orb slows every enemy in its burst.",
        42.,
        8,
        0.75,
        2.2,
        1,
        32.,
        0.01,
        3.5,
        17.,
        1,
        0.12
    ),
    w!(
        "SOUL LANTERN",
        4,
        Lantern,
        Drain,
        "A narrow soul beam restores health on contact.",
        19.,
        25,
        0.19,
        2.4,
        1,
        18.,
        0.,
        0.,
        0.,
        1,
        0.
    ),
    w!(
        "PLAGUE CENSER",
        4,
        Lantern,
        Poison,
        "Lob a venom orb; its blast poisons a crowd.",
        26.,
        6,
        0.9,
        2.6,
        1,
        26.,
        0.015,
        4.5,
        11.,
        1,
        0.
    ),
    w!(
        "OSSUARY CROSSBOW",
        2,
        Crossbow,
        Pierce,
        "A fast bone bolt pierces multiple targets.",
        75.,
        1,
        1.,
        1.35,
        1,
        55.,
        0.002,
        0.,
        38.,
        1,
        0.3
    ),
    w!(
        "MOON LONGBOW",
        2,
        Bow,
        Pierce,
        "Long-reaching arrows, steady rhythm, no magazine.",
        64.,
        1,
        0.8,
        0.65,
        1,
        60.,
        0.002,
        0.,
        34.,
        1,
        0.2
    ),
    w!(
        "BUTCHER CLEAVER",
        5,
        Blade,
        Impact,
        "A broad sweep cleaves every enemy within reach.",
        65.,
        0,
        0.75,
        0.,
        1,
        2.8,
        0.35,
        0.,
        0.,
        1,
        0.6
    ),
    w!(
        "THORN RAPIER",
        5,
        Rapier,
        Pierce,
        "A fast narrow thrust lunges into its target.",
        48.,
        0,
        0.39,
        0.,
        1,
        3.8,
        0.92,
        0.,
        0.,
        1,
        0.18
    ),
    w!(
        "GRAVEBELL HAMMER",
        5,
        Hammer,
        Blast,
        "A weighty slam blasts nearby enemies backward.",
        100.,
        0,
        1.2,
        0.,
        1,
        3.,
        0.50,
        3.2,
        0.,
        1,
        2.
    ),
    w!(
        "REAPER SCYTHE",
        5,
        Scythe,
        Drain,
        "A wide, long sweep steals life from the crowd.",
        52.,
        0,
        0.95,
        0.,
        1,
        4.1,
        -0.1,
        0.,
        0.,
        1,
        0.4
    ),
    w!(
        "PENITENT FLAIL",
        5,
        Flail,
        Impact,
        "A sweeping chain reaches beyond a normal blade.",
        72.,
        0,
        0.88,
        0.,
        1,
        4.5,
        0.20,
        0.,
        0.,
        1,
        1.2
    ),
    w!(
        "WIDOW FANGS",
        5,
        Daggers,
        Poison,
        "Alternating close-range cuts build venom damage.",
        24.,
        0,
        0.23,
        0.,
        1,
        2.3,
        0.60,
        0.,
        0.,
        1,
        0.05
    ),
];
impl WeaponKind {
    pub const ALL: [Self; 33] = [
        Self::Pistol,
        Self::Double,
        Self::Repeater,
        Self::GraveRevolver,
        Self::Duelist,
        Self::Pepperbox,
        Self::HandCannon,
        Self::Needler,
        Self::Blunderbuss,
        Self::Coachgun,
        Self::SlugGun,
        Self::Dragonbreath,
        Self::Frostbite,
        Self::Longrifle,
        Self::Carbine,
        Self::Gatling,
        Self::Harpoon,
        Self::Ricochet,
        Self::GrenadeLauncher,
        Self::Mortar,
        Self::EmberStaff,
        Self::StormWand,
        Self::FrostScepter,
        Self::SoulLantern,
        Self::PlagueCenser,
        Self::Crossbow,
        Self::Longbow,
        Self::Cleaver,
        Self::Rapier,
        Self::Warhammer,
        Self::Scythe,
        Self::ChainFlail,
        Self::TwinDaggers,
    ];
    pub fn spec(self) -> &'static Spec {
        &SPECS[self as usize]
    }
    pub fn melee(self) -> bool {
        self.spec().group == 5
    }
    pub fn base(self) -> Self {
        match self.spec().model {
            Model::Shotgun => Self::Double,
            Model::Pistol | Model::Revolver | Model::Needle => Self::Pistol,
            _ => Self::Repeater,
        }
    }
    /// Creatures one shot can pass through, nearest first; each after the
    /// first takes 18% less than the one before.
    pub fn pierce_limit(self) -> usize {
        match self {
            _ if self.spec().effect != Effect::Pierce || self.melee() => 1,
            Self::Duelist => 2,
            Self::SlugGun => 3,
            _ => 4,
        }
    }
    /// Further creatures a chain jumps to, each the nearest within
    /// `spec().radius` of the last; each jump takes 28% less.
    pub fn chain_jumps(self) -> usize {
        match self {
            _ if self.spec().effect != Effect::Chain => 0,
            Self::StormWand => 3,
            _ => 2,
        }
    }
    /// A melee swing's width: it hits every creature in front within
    /// `spec().range` whose bearing is inside this many degrees.
    pub fn sweep_degrees(self) -> f32 {
        2. * self.spec().spread.clamp(-1., 1.).acos().to_degrees()
    }
    /// How far an attack reaches beyond one creature, for the card face, or
    /// `None` for one creature (or a scattergun's pellets, which the card
    /// counts already).
    pub fn reach(self) -> Option<String> {
        let s = self.spec();
        if self.melee() {
            let sweep = format!("{:.0}° SWEEP", self.sweep_degrees());
            return Some(if s.radius > 0. {
                format!("{sweep} + {:.1}m SPLASH", s.radius)
            } else {
                sweep
            });
        }
        match s.effect {
            Effect::Pierce => Some(format!("PIERCES {}", self.pierce_limit())),
            Effect::Chain => Some(format!(
                "CHAINS TO {} MORE IN {:.1}m",
                self.chain_jumps(),
                s.radius
            )),
            _ if s.radius > 0. => Some(format!("{:.1}m SPLASH", s.radius)),
            _ => None,
        }
    }
    pub fn tint(self) -> [f32; 3] {
        match self.spec().effect {
            Effect::Burn => [3., 0.4, 0.03],
            Effect::Frost => [0.15, 1.3, 2.8],
            Effect::Poison => [0.4, 2., 0.05],
            Effect::Chain => [0.65, 0.4, 3.],
            Effect::Drain => [0.1, 2., 1.3],
            _ => [2., 1.2, 0.2],
        }
    }
}
